/* eslint-disable quote-props */
import {css} from '@emotion/react';

export default {
  toggleIcon: css({
    width: '16px',
    verticalAlign: 'middle',
  }),
  toggle: css({
    display: 'none',
    cursor: 'pointer',
  }),
  search: css({
    width: '100%',
    height: 'auto',
    padding: '1.5em 1em 2.5em',
    margin: '2em auto',
    color: '#6a5050',
    border: 'dashed 2px #573333b3', // 点線
    background: 'rgb(255, 255, 255)',
    // boxShadow: '0 2px 5px rgba(81, 51, 30, 0.689)',
    textAlign: 'center',
  }),
  menu: css({
    width: '70%',
    // display: 'none',
    margin: '2em auto',
    listStyle: 'none',
  }),
  genre: css({
    float: 'left',
    marginLeft: '2%',
  }),
  checkGenre: css({
    boxSizing: 'border-box',
    cursor: 'pointer',
    display: 'inline-block',
    padding: '5px 25px',
    position: 'relative',
    width: 'auto',
    // before
    '&:before': {
      background: '#fff',
      border: '1px solid #231815',
      content: '""',
      display: 'block',
      height: '16px',
      left: '5px',
      marginTop: '-8px',
      position: 'absolute',
      top: '50%',
      width: '16px',
    },
    // after
    '&:after': {
      borderRight: '3px solid #ed7a9c',
      borderBottom: '3px solid #ed7a9c',
      content: '""',
      display: 'block',
      height: '9px',
      left: '10px',
      marginTop: '-6px',
      opacity: 0,
      position: 'absolute',
      top: '50%',
      transform: 'rotate(45deg)',
      width: '5px',
    },
  }),
  colorGenre: css({
    boxSizing: 'border-box',
    cursor: 'pointer',
    display: 'inline-block',
    padding: '5px 10px 5px 30px',
    position: 'relative',
    width: 'auto',
    backgroundColor: '#d9f0f7',
    borderRadius: '10px',
    letterSpacing: '1px',
    ':before': {
      background: '#fff',
      border: '2px solid #6a5050',
      content: '""',
      display: 'block',
      borderRadius: '20px',
      height: '20px',
      left: '2px',
      marginTop: '-10px',
      position: 'absolute',
      top: '50%',
      width: '20px',
    },
    ':after': {
      borderTight: '3px solid #6a5050',
      borderBottom: '3px solid #6a5050',
      content: '""',
      display: 'block',
      height: '9px',
      left: '10px',
      marginTop: '-6px',
      opacity: 0,
      position: 'absolute',
      top: '50%',
      transform: 'rotate(45deg)',
      width: '5px',
    },
  }),
  list: css({
    display: 'flex',
  }),
  listSearch: css({
    display: 'block',
    width: '100%',
    margin: '22px auto',
    height: '1px',
    backgroundColor: '#8c6e6e',
    border: 0,
  }),
  sub: css({
    display: 'block',
    marginLeft: '10%',
  }),
  mainTitle: css({
    color: '#6A5050',
    margin: '60px auto',
    textAlign: 'center',
    width: '60%',
  }),
};
