name: Jest
on:
  push:
    branches:
      - '!main'
jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: ci
        run: export NODE_ENV=test && yarn install --immutable --immutable-cache --check-cache
      - name: jest
        run: yarn test
